[CardsMongoDB] Fix 500 error in /browse due to missing textScore
```log
MongoError: query requires text score metadata, but it is not available
    at Connection.<anonymous> (/Users/dchege711/study_buddy/node_modules/mongoose/node_modules/mongodb/lib/core/connection/pool.js:453:61)
    at Connection.emit (node:events:513:28)
    at Connection.emit (node:domain:489:12)
    at processMessage (/Users/dchege711/study_buddy/node_modules/mongoose/node_modules/mongodb/lib/core/connection/connection.js:456:10)
    at Socket.<anonymous> (/Users/dchege711/study_buddy/node_modules/mongoose/node_modules/mongodb/lib/core/connection/connection.js:625:15)
    at Socket.emit (node:events:513:28)
    at Socket.emit (node:domain:489:12)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at Socket.Readable.push (node:internal/streams/readable:234:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {
  ok: 0,
  code: 40218,
  codeName: 'Location40218'
}
```

[1] notes that textScore is only available when used in conjunction with
a $text query.

[1]: https://www.mongodb.com/docs/manual/reference/operator/aggregation/meta/