[ES] Update webpack to fix ERR_OSSL_EVP_UNSUPPORTED build error
Resolves this error in `npm run build`:

```log
> flashcards_by_c13u@1.0.0 build
> webpack --config webpack.config.js

clean-webpack-plugin: /Users/dchege711/study_buddy/dist has been removed.
node:internal/crypto/hash:71
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (/Users/dchege711/study_buddy/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/Users/dchege711/study_buddy/node_modules/webpack/lib/NormalModule.js:417:16)
    at handleParseError (/Users/dchege711/study_buddy/node_modules/webpack/lib/NormalModule.js:471:10)
    at /Users/dchege711/study_buddy/node_modules/webpack/lib/NormalModule.js:503:5
    at /Users/dchege711/study_buddy/node_modules/webpack/lib/NormalModule.js:358:12
    at /Users/dchege711/study_buddy/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/Users/dchege711/study_buddy/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at iterateNormalLoaders (/Users/dchege711/study_buddy/node_modules/loader-runner/lib/LoaderRunner.js:221:10)
    at /Users/dchege711/study_buddy/node_modules/loader-runner/lib/LoaderRunner.js:236:3
    at context.callback (/Users/dchege711/study_buddy/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at /Users/dchege711/study_buddy/node_modules/babel-loader/lib/index.js:44:71 {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v18.14.0
```

[1]: https://stackoverflow.com/questions/69394632/webpack-build-failing-with-err-ossl-evp-unsupported/69691525#69691525