[TestCardsMongoDB] Fix typing error
```log
src/tests/mocha_tests/unit_tests/TestCardsMongoDB.ts:89:9 - error TS2322: Type 'ICardRaw' is not assignable to type 'ICard'.
  Type 'ICardRaw' is missing the following properties from type 'Document<any, any, ICardRaw>': $getAllSubdocs, $ignore, $isDefault, $isDeleted, and 48 more.

89         card = await CardsDB.update(card);
           ~~~~

src/tests/mocha_tests/unit_tests/TestCardsMongoDB.ts:93:9 - error TS2322: Type 'ICardRaw' is not assignable to type 'ICard'.

93         card = await CardsDB.update(card);
           ~~~~
```