git mv Autocomplete.ts AutoComplete.ts
Obtained tip from [1]. Mac is not case-sensitive by default [2] and thus
we need an explicit `git mv` command.

```log
src/public/src/AutoComplete.test.ts:3:30 - error TS1261: Already included file name '/Users/dchege711/study_buddy/src/public/src/AutoComplete.ts' differs from file name '/Users/dchege711/study_buddy/src/public/src/Autocomplete.ts' only in casing.
  The file is in the program because:
    Imported via "./AutoComplete" from file '/Users/dchege711/study_buddy/src/public/src/AutoComplete.test.ts'
    Matched by include pattern './src/**/*' in '/Users/dchege711/study_buddy/tsconfig.json'
    Imported via "./AutoComplete" from file '/Users/dchege711/study_buddy/src/public/src/BrowseCardsPage.ts'
    Imported via "./AutoComplete" from file '/Users/dchege711/study_buddy/src/public/src/HomePage.ts'
    Imported via "./AutoComplete" from file '/Users/dchege711/study_buddy/src/public/src/TagsBarTemplate.ts'

3 import { AutoComplete } from "./AutoComplete";
                               ~~~~~~~~~~~~~~~~

  tsconfig.json:11:17
    11     "include": ["./src/**/*"]
                       ~~~~~~~~~~~~
    File is matched by include pattern specified here.
  src/public/src/BrowseCardsPage.ts:5:30
    5 import { AutoComplete } from "./AutoComplete";
                                   ~~~~~~~~~~~~~~~~
    File is included via import here.
  src/public/src/HomePage.ts:7:30
    7 import { AutoComplete } from "./AutoComplete";
                                   ~~~~~~~~~~~~~~~~
    File is included via import here.
  src/public/src/TagsBarTemplate.ts:1:30
    1 import { AutoComplete } from "./AutoComplete";
                                   ~~~~~~~~~~~~~~~~
    File is included via import here.

Found 1 error in src/public/src/AutoComplete.test.ts:3
```

[1]: https://stackoverflow.com/questions/17683458/how-do-i-commit-case-sensitive-only-filename-changes-in-git
[2]: https://discussions.apple.com/thread/251191099?sortBy=best