Revert "[Server] Make server a module and fix all TS errors"
This reverts commit 570062229b83922a2428af2cd7e04fcd22ee9fdd.

I'm having trouble with ESM on the server, and I'm not alone [1]. Will
try to fix this later.

```log
(base) ~/study_buddy $ npm run start

> flashcards_server@1.0.0 start
> npm run build && node dist/server.js

> flashcards_server@1.0.0 build
> tsc --project tsconfig.json

file:///Users/dchege711/study_buddy/dist/models/mongoose_models/CardSchema.js:6
import { model, Schema } from "mongoose";
                ^^^^^^
SyntaxError: Named export 'Schema' not found. The requested module 'mongoose' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from 'mongoose';
const { model, Schema } = pkg;

    at ModuleJob._instantiate (node:internal/modules/esm/module_job:124:21)
    at async ModuleJob.run (node:internal/modules/esm/module_job:190:5)

Node.js v18.14.0
```

[1]: https://www.reddit.com/r/node/comments/14rg9ym/esm_not_gaining_traction_in_backend_node/