[!Debug] Exclude AutoComplete from webpack to debug Github Action
`npm run build --if-present` is already failing with:

```log
> flashcards_by_c13u@1.0.0 build /home/runner/work/study_buddy/study_buddy
> webpack --config webpack.config.js

clean-webpack-plugin: /home/runner/work/study_buddy/study_buddy/dist has been removed.
circular-dependency-plugin: looking for webpack modules cycles...

Insufficient number of arguments or no entry found.
Alternatively, run 'webpack(-cli) --help' for usage info.

Hash: c2beed6ce5c73921e827
Version: webpack 4.25.1
Time: 1531ms
Built at: 10/25/2022 7:25:01 AM
 4 assets
Entrypoint CardTemplateUtilities = CardTemplateUtilities.bundle.min.js
Entrypoint CardsManager = CardsManager.bundle.min.js
Entrypoint AppUtilities = AppUtilities.bundle.min.js
Entrypoint TagsBarUtilities = TagsBarUtilities.bundle.min.js
[0] ./public/src/AppUtilities.js 4.31 KiB {0} {2} [built]
[1] ./public/src/CardTemplateUtilities.js 2.03 KiB {1} [built]
[2] ./public/src/CardsManager.js 12.1 KiB {2} [built]
[3] ./public/src/AVLTree.js 20.8 KiB {2} [built]
[4] ./public/src/TagsBarUtilities.js 2.78 KiB {3} [built]

ERROR in Entry module not found: Error: Can't resolve '/home/runner/work/study_buddy/study_buddy/public/src/AutoComplete.js' in '/home/runner/work/study_buddy/study_buddy'
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! flashcards_by_c13u@1.0.0 build: `webpack --config webpack.config.js`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the flashcards_by_c13u@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/runner/.npm/_logs/2022-10-25T07_25_01_730Z-debug.log
Error: Process completed with exit code 2.
```

Pushing this commit to test if the problem is isolated to AutoComplete.