[search-bar.test] Sample test that needs server (or mocking)
`npm test src/components/search-bar/search-bar.test.ts` fails with:

```log
src/components/search-bar/search-bar.test.ts:

 🚧 Browser logs:
      Lit is in dev mode. Not recommended for production! See https://lit.dev/msg/dev-mode for more information.
      An error was thrown in a Promise outside a test. Did you forget to await a function or assertion?
      TRPCClientError: Unexpected token 'N', "Not Found" is not valid JSON
        at TRPCClientError.from (../../node_modules/@trpc/client/dist/TRPCClientError.mjs:37:16)
        at ../../node_modules/@trpc/client/dist/links/internals/httpUtils.mjs:110:36

 🚧 404 network requests:
    - trpc/searchPublicCards?batch=1&input=%7B%220%22%3A%7B%22limit%22%3Anull%2C%22queryString%22%3A%22%22%7D%7D

 ❌ search-bar > should fetch initial results on load
      Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
        at createTimeoutError (../../node_modules/@web/test-runner-mocha/dist/autorun.js:1:191473)
        at ds._timeoutError (../../node_modules/@web/test-runner-mocha/dist/autorun.js:1:195706)
        at ../../node_modules/@web/test-runner-mocha/dist/autorun.js:1:193787
```

... because the test is trying to fetch data from the server.