Revert "[Lint] Intentionally add no-unused-vars violation to test CI"
This reverts commit 17e9ce911a019e32da7cb0152187f909abbb3dea.

CI failed successfully [1].

```log
Run npm run lint
> flashcards_server@1.0.0 lint
> eslint .
/home/runner/work/study_buddy/study_buddy/src/config.ts
Error:   5:7  error  'someUnusedVariable' is assigned a value but never used  @typescript-eslint/no-unused-vars
✖ 1 problem (1 error, 0 warnings)
Error: Process completed with exit code 1.
```

[1]: https://github.com/dchege711/study_buddy/actions/runs/9816616879/job/27107033207?pr=191