[TestLogIn] Type this as Suite
CI is failing with:

```log
Error: src/tests/mocha_tests/functionality_tests/TestLogIn.ts(8,43): error TS2345: Argument of type '(this: Mocha.Context) => void' is not assignable to parameter of type '(this: Suite) => void'.
  The 'this' types of each signature are incompatible.
    Type 'Suite' is missing the following properties from type 'Context': _runnable, runnable, skip
```