Revert "[graph.test] Intentional test break to debug test logs"
The logs are working as expected, erroring out in the TS file:

```log
src/models/core/graph.test.ts:

 ❌ Test Graph
 > should have undirected edges
      AssertionError: expected 2 to equal 3
      + expected - actual

      -2
      +3

      at n.<anonymous> (src/models/core/graph.test.ts:11:42)
```

This reverts commit 202165525c69dc09dd483f451d00c5e5a11f0c77.