[ES] Add NODE_ENV="development" env var for node.js.yml
Should solve this failure in the `npm run test` step of Github Actions:

```log
> flashcards_by_c13u@1.0.0 test /home/runner/work/study_buddy/study_buddy
> node models/Miscellaneous.js && npm run mocha_tests

/home/runner/work/study_buddy/study_buddy/config.js:16
    throw Error("Please set the NODE_ENV environment variable.");
    ^

Error: Please set the NODE_ENV environment variable.
    at Object.<anonymous> (/home/runner/work/study_buddy/study_buddy/config.js:16:11)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:101:18)
    at Object.<anonymous> (/home/runner/work/study_buddy/study_buddy/models/MetadataMongoDB.js:14:16)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:101:18)
    at Object.<anonymous> (/home/runner/work/study_buddy/study_buddy/models/Miscellaneous.js:11:20)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
npm ERR! Test failed.  See above for more details.
Error: Process completed with exit code 1.
```