[Mongoose] Pass `unique: true` instead of `unique: [true, "x must be unique"]`
Fixes these errors:

```log
src/models/mongoose_models/Token.ts:19:5 - error TS2322: Type '{ type: StringConstructor; required: true; unique: (string | true)[]; }' is not assignable to type 'SchemaDefinitionProperty<string> | undefined'.
  Types of property 'unique' are incompatible.
    Type '(string | true)[]' is not assignable to type 'number | boolean | undefined'.

19     token_id: {
       ~~~~~~~~

src/models/mongoose_models/UserSchema.ts:28:5 - error TS2322: Type '{ type: StringConstructor; required: true; unique: (string | true)[]; immutable: true; match: RegExp; }' is not assignable to type 'SchemaDefinitionProperty<string> | undefined'.
  Types of property 'unique' are incompatible.
    Type '(string | true)[]' is not assignable to type 'number | boolean | undefined'.

28     username: {
       ~~~~~~~~
```

AFAICT, the custom string doesn't seem like it was ever supported in v5 [1].

[1]: https://mongoosejs.com/docs/5.x/docs/validation.html#the-unique-option-is-not-a-validator