[ES] Try using cd instead of pushd and popd
[1] failed with:

```log
> flashcards_server@1.0.0 build:client
> pushd src/public && npm run build && popd

sh: 1: pushd: not found
Error: Process completed with exit code 127.
```

This is a speculative fix.

[1]: https://github.com/dchege711/study_buddy/actions/runs/9431492588/job/25980205770?pr=152