[Mongoose] Fix Card.findOne typing
Resolves this build error:

```log
src/models/CardsMongoDB.ts:86:23 - error TS2769: No overload matches this call.
  Overload 1 of 3, '(filter?: FilterQuery<ICardRaw> | undefined, projection?: ProjectionType<ICardRaw> | null | undefined, options?: QueryOptions<ICardRaw> | null | undefined, callback?: Callback<...> | undefined): Query<...>', gave the following error.
    Argument of type 'Partial<ICard>' is not assignable to parameter of type 'FilterQuery<ICardRaw>'.
      Type 'Partial<ICard>' is not assignable to type 'RootQuerySelector<ICardRaw>'.
        Types of property '$where' are incompatible.
          Type 'Record<string, unknown> | undefined' is not assignable to type 'string | Function | undefined'.
            Type 'Record<string, unknown>' is not assignable to type 'string | Function | undefined'.
              Type 'Record<string, unknown>' is missing the following properties from type 'Function': apply, call, bind, prototype, and 5 more.
  Overload 2 of 3, '(filter?: FilterQuery<ICardRaw> | undefined, projection?: ProjectionType<ICardRaw> | null | undefined, callback?: Callback<(Document<unknown, any, ICardRaw> & Omit<...>) | null> | undefined): Query<...>', gave the following error.
    Argument of type 'Partial<ICard>' is not assignable to parameter of type 'FilterQuery<ICardRaw>'.
  Overload 3 of 3, '(filter?: FilterQuery<ICardRaw> | undefined, callback?: Callback<(Document<unknown, any, ICardRaw> & Omit<ICardRaw & Required<{ _id: string; }>, never>) | null> | undefined): Query<...>', gave the following error.
    Argument of type 'Partial<ICard>' is not assignable to parameter of type 'FilterQuery<ICardRaw>'.

86   return Card.findOne(query).select(projection).exec();
                         ~~~~~
```