Revert "[Formatting] Deliberately fail format:check"
This reverts commit 203043b88efcf6a88cd92f50995c2ab14e453ec1.

Confirmed that it fails CI [1]:

```log
Run npm run format:check

> flashcards_server@1.0.0 format:check
> dprint check

Compiling https://plugins.dprint.dev/markdown-0.17.1.wasm
Compiling https://plugins.dprint.dev/json-0.19.3.wasm
Compiling https://plugins.dprint.dev/typescript-0.91.1.wasm
from /home/runner/work/study_buddy/study_buddy/src/public/src/components/card-viewer/components/copyable.ts:
35 35|
36 36| declare·global·{
37 37| ··interface·HTMLElementTagNameMap·{
   38|-····'cg-copyable':·CopyableElement;
38   |+····"cg-copyable":·CopyableElement;
39 39| ··}
40 40| }
--
Found 1 not formatted file.
Error: Process completed with exit code 20.
```

[1]: https://github.com/dchege711/study_buddy/actions/runs/9439727566/job/25998178490?pr=161